# Generated by Django 4.2.10 on 2025-06-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_ultrasound_remove_medicine_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultrasoundappointment',
            name='auto_token_number',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
