# Generated by Django 4.2.10 on 2025-06-02 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_ultrasoundappointment_auto_token_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ultrasoundappointment',
            name='token_number',
        ),
    ]
